from rest_framework import serializers
from backend_api.models import Product


class ProductSerializer(serializers.ModelSerializer):
    class Meta:
        model = Product
        fields = '__all__'
        # fields = ('id',
        #           'product_title',
        #           'deposit_start_time',
        #           'view_start_time',
        #           'auction_start_time',
        #           'auction_end_time',
        #           'product_type',
        #           'product_kind',
        #           'product_name',
        #           'product_begin_prize',
        #           'product_step_prize',
        #           # 'product_loc_city',
        #           # 'product_loc_district',
        #           # 'product_loc_wards',
        #           # 'product_loc_street',
        #           # 'product_detail_data',
        #           # 'product_owner_type',
        #           # 'product_owner_name',
        #           # 'product_owner_business_regis_no',
        #           # 'product_owner_business_regis_no_date',
        #           # 'product_owner_business_regis_no_place',
        #           # 'product_owner_tax_code',
        #           # 'product_owner_phone',
        #           # 'product_owner_email',
        #           # 'product_owner_city',
        #           # 'product_owner_district',
        #           # 'product_owner_wards',
        #           # 'product_owner_street',
        #           # 'product_owner_represent_surname',
        #           # 'product_owner_represent_name',
        #           # 'product_owner_represent_position',
        #           # 'product_owner_represent_phone',
        #           # 'product_owner_represent_email',
        #           # 'product_owner_represent_gender',
        #           # 'product_owner_represent_dob',
        #           # 'product_owner_represent_id_card',
        #           # 'product_owner_represent_id_card_date',
        #           # 'product_owner_represent_id_card_place',
        #           # # 'product_owner_represent_id_card_image_front',
        #           # # 'product_owner_represent_id_card_image_back',
        #           # 'product_owner_represent_bank_no',
        #           # 'product_owner_represent_bank_name',
        #           # 'product_owner_represent_bank_branch',
        #           # 'product_owner_represent_bank_user_name'
        #
        #           )
        # extra_kwargs = {'id' : {'read_only': True},
        #           'product_title' : {'required': False},
        #           'deposit_start_time' : {'required': False},
        #           'view_start_time' : {'required': False},
        #           'auction_start_time' : {'required': False},
        #           'auction_end_time' : {'required': False},
        #           'product_type' : {'required': False},
        #           'product_kind' : {'required': False},
        #           'product_name' : {'required': False},
        #           'product_begin_prize' : {'required': False},
        #           'product_step_prize' : {'required': False},
        #           'product_loc_city' : {'required': False},
        #           'product_loc_district' : {'required': False},
        #           'product_loc_wards' : {'required': False},
        #           'product_loc_street' : {'required': False},
        #           'product_detail_data' : {'required': False},
        #           'product_owner_type' : {'required': False},
        #           'product_owner_name' : {'required': False},
        #           'product_owner_business_regis_no' : {'required': False},
        #           'product_owner_business_regis_no_date' : {'required': False},
        #           'product_owner_business_regis_no_place' : {'required': False},
        #           'product_owner_tax_code' : {'required': False},
        #           'product_owner_phone' : {'required': False},
        #           'product_owner_email' : {'required': False},
        #           'product_owner_city' : {'required': False},
        #           'product_owner_district' : {'required': False},
        #           'product_owner_wards' : {'required': False},
        #           'product_owner_street' : {'required': False},
        #           'product_owner_represent_surname' : {'required': False},
        #           'product_owner_represent_name' : {'required': False},
        #           'product_owner_represent_position' : {'required': False},
        #           'product_owner_represent_phone' : {'required': False},
        #           'product_owner_represent_email' : {'required': False},
        #           'product_owner_represent_gender' : {'required': False},
        #           'product_owner_represent_dob' : {'required': False},
        #           'product_owner_represent_id_card' : {'required': False},
        #           'product_owner_represent_id_card_date' : {'required': False},
        #           'product_owner_represent_id_card_place' : {'required': False},
        #           # 'product_owner_represent_id_card_image_front' : {'required': False},
        #           # 'product_owner_represent_id_card_image_back' : {'required': False},
        #           'product_owner_represent_bank_no' : {'required': False},
        #           'product_owner_represent_bank_name' : {'required': False},
        #           'product_owner_represent_bank_branch' : {'required': False},
        #           'product_owner_represent_bank_user_name' : {'required': False}
        # }
